name: windowshoppi
description: A new Flutter application.

version: 1.0.5+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_staggered_grid_view: ^0.3.4
  transparent_image: ^2.0.0
  url_launcher: ^6.0.2
  flutter_open_whatsapp: ^0.1.2
  flutter_share_me: ^0.9.2
  custom_navigator: ^0.3.0
  custom_navigation_bar: ^0.8.0
  connectivity: ^3.0.3
  google_maps_webservice: ^0.0.20-nullsafety.2
  rxdart: ^0.26.0
  http: ^0.13.1
#  multi_image_picker: ^4.7.14
  multi_image_picker: ^4.8.0
  carousel_pro: ^1.0.0
  sqflite: ^2.0.0+3
#  path_provider: ^1.6.11
  path_provider: ^2.0.1
#  shared_preferences: ^0.5.8
  shared_preferences: ^2.0.5
#  shimmer: ^1.1.1
  shimmer: ^1.1.2
  sentry: ^3.0.1
  geolocator: ^6.2.1
#  extended_image: ^1.3.0
  extended_image: ^3.0.0
  equatable: ^1.2.5
  flutter_bloc: ^7.0.0
  provider: ^5.0.0
  animations: ^2.0.0
  introduction_screen: ^2.0.0
  international_phone_input: ^1.0.4
  intl_phone_number_input: ^0.6.0
  data_connection_checker: ^0.3.4
  fluttertoast: ^8.0.3
  flutter_phoenix: ^1.0.0
  page_transition: ^1.1.7+6
  scrollable_positioned_list: ^0.1.10
  line_awesome_flutter: ^1.0.1


#  font_awesome_flutter: ^8.10.1
#  flutter_staggered_grid_view: ^0.3.2
#  transparent_image: ^1.0.0
#  url_launcher: ^5.7.10
#  flutter_open_whatsapp: ^0.1.2
#  flutter_share_me: ^0.9.2
#  custom_navigator: ^0.3.0
#  custom_navigation_bar: ^0.6.0
#  connectivity: ^0.4.8+6
#  google_maps_webservice: ^0.0.16
#  rxdart: ^0.24.1
#  http: ^0.12.2
#  multi_image_picker: ^4.7.14
#  carousel_pro: ^1.0.0
#  sqflite: ^1.3.1
#  path_provider: ^1.6.11
#  shared_preferences: ^0.5.8
#  shimmer: ^1.1.1
#  sentry: ^3.0.1
#  geolocator: ^5.3.2+2
#  extended_image: ^1.3.0
#  equatable: ^1.2.5
#  flutter_bloc: ^6.0.6
#  provider: ^4.3.2+2
#  animations: ^1.1.2
#  introduction_screen: ^1.0.9
#  flushbar: ^1.10.4
#  international_phone_input: ^1.0.4
#  intl_phone_number_input: ^0.5.2+2
#  data_connection_checker: ^0.3.4
#  fluttertoast: ^7.1.8
#  flutter_phoenix: ^0.1.0
#  page_transition: "^1.1.7+6"
#  scrollable_positioned_list: ^0.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

    - family: Itim
      fonts:
        - asset: fonts/Itim-Regular.ttf

  assets:
    - assets/logo/
    - assets/image/