name: windowshoppi
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_staggered_grid_view: ^0.3.4
  transparent_image: ^2.0.0
  url_launcher: ^6.0.2
  flutter_open_whatsapp: ^0.1.2
  flutter_share_me: ^0.9.2
  custom_navigator: ^0.3.0
  custom_navigation_bar: ^0.8.0
  connectivity: ^3.0.3
  google_maps_webservice: ^0.0.20-nullsafety.2
  rxdart: ^0.26.0
  http: ^0.13.1
  multi_image_picker: ^4.8.0
  carousel_pro: ^1.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^1.1.2
  sentry: ^3.0.1
  #  geolocator: ^6.2.1
  extended_image: ^3.0.0
  equatable: ^1.2.5
  flutter_bloc: ^7.0.0
  provider: ^5.0.0
  animations: ^2.0.0
  introduction_screen: ^2.0.0
  international_phone_input: ^1.0.4
  #  intl_phone_number_input: ^0.6.0
  intl_phone_number_input: ^0.5.2+2
  data_connection_checker: ^0.3.4
  fluttertoast: ^8.0.3
  flutter_phoenix: ^1.0.0
  page_transition: ^1.1.7+6
  scrollable_positioned_list: ^0.1.10
  line_awesome_flutter: ^1.0.1
  firebase_messaging: ^10.0.1
  firebase_core: ^1.2.1
  flutter_local_notifications: ^5.0.0+4
  cloud_firestore: ^1.0.7
  uuid: ^3.0.4
  webview_flutter: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
