const SERVER_NAME = "http://192.168.1.83:8000";
// const SERVER_NAME = "http://3.17.145.13/"; // production ip address

const ALL_PRODUCT_URL = "$SERVER_NAME/post/all/";
const POST_API = "$SERVER_NAME/post/post-list/";
const ALL_COUNTRY_URL = "$SERVER_NAME/master_data/country/";
const TOP30_CATEGORY = "$SERVER_NAME/master_data/top30category/";
const ALL_CATEGORY = "$SERVER_NAME/master_data/allCategory/";
const CREATE_POST = "$SERVER_NAME/post/create/";
const SEARCH_POST = "$SERVER_NAME/post/search/";
const VENDOR_POST = "$SERVER_NAME/post/vendor/";
const BUSINESS_INFO = "$SERVER_NAME/business/";
const VALIDATE_USERNAME = "$SERVER_NAME/validate/";
const REGISTER_USER = "$SERVER_NAME/register/";
const LOGIN_USER = "$SERVER_NAME/login/";
const USER_LOGIN = "$SERVER_NAME/user-login/";
const UPDATE_PROFILE = "$SERVER_NAME/update/";
const UPDATE_POST = "$SERVER_NAME/post/update-post/";
const USER_DATA = "$SERVER_NAME/user-data/";
